// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const CHANGE_AUTH_EMAIL = 'CHANGE_AUTH_EMAIL';
export const CHANGE_AUTH_PASSWORD = 'CHANGE_AUTH_PASSWORD';
export const START_ASYNC_AUTH = 'START_ASYNC_AUTH';
export const END_ASYNC_AUTH = 'END_ASYNC_AUTH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// base
export const REPLACE_BUILDING = 'REPLACE_BUILDING';
export const REPLACE_ALL_BASE = 'REPLACE_ALL_BASE';
export const REPLACE_BASE_FROM_URL = 'REPLACE_BASE_FROM_URL';
export const CHANGE_FRACTION = 'CHANGE_FRACTION';
export const BUILDING_TYP_UP = 'BUILDING_TYP_UP';
export const BUILDING_TYP_DOWN = 'BUILDING_TYP_DOWN';
export const SWITCH_BUILDINGS = 'SWITCH_BUILDINGS';
export const SWITCH_SLOT = 'SWITCH_SLOT';

// player
export const PLAYER_CHANGE_WORLD = 'PLAYER_CHANGE_WORLD';
export const PLAYER_CHANGE_SELECTED_BASE = 'PLAYER_CHANGE_SELECTED_BASE';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';
export const PLAYER_UPDATE_BASES = 'PLAYER_UPDATE_BASES';
export const PLAYER_CHANGE_LOADING = 'PLAYER_CHANGE_LOADING';
export const PLAYER_UPDATE_ALLIANCE_ID = 'PLAYER_UPDATE_ALLIANCE_ID';
