# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



// delete layoyuts behind some day's
GET http://{{host}}/api/v1/db
Content-Type: application/json

###

// delete layoyuts behind some day's
GET http://{{host}}/api/v1/db/deleteOldLayouts/-1
Authorization: Bearer

###

// delete layoyuts behind some day's
GET http://{{host}}/api/v1/db/deleteOldReports/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2NhbCI6eyJlbWFpbCI6Imp1bGlhbi5saWJvckBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCRMUUJsL20zMFFNUFIyOElDLlJib3QuN0ZRaHk0SlZLbzk3RWhvdlFUaTdTdy45ZG9kTURMQyJ9LCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoicGxheWVyIiwiX2lkIjoiNWQ1NWNjYWQzM2M0MWM3NjIwYmY3OWE5Iiwid29ybGRzIjpbeyJfaWQiOiI1ZDcyY2I5NzFmYTk0ODNjZDhlMmQ5ZjkiLCJ3b3JsZElkIjozNzMsIndvcmxkTmFtZSI6IldvcmxkIENoYW1waW9uc2hpcCAyMDE3IiwicGxheWVyX2lkIjoiNWNmYjgzY2M1MTFjMDM5ZGYwZWRjNjdiIiwiYWxsaWFuY2VJZCI6MTI2fV0sIl9fdiI6NTUsInBsYXllciI6ImxpbnV4MjQ5IiwicGxheWVyQWRkZWQiOiIyMDE5LTA4LTIxVDIwOjEzOjE4LjM3N1oiLCJpYXQiOjE1Njc5Nzc4MTR9.McAb6ZvWvszJ-yQI1xjUzzUp21-YH5nkCO0TP51l9oE

###


// update all users worlds
GET http://{{host}}/api/v1/db/updateAllUsersWorlds
Authorization: Bearer

###


// create a new report
GET http://{{host}}/api/v1/db/createReport
Authorization: Bearer

###

// get the footer stats
GET http://{{host}}/api/v1/db/getFooterStats
Authorization: Bearer

###

