# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



// delete layoyuts behind some day's
GET http://{{host}}/api/v1/db
Content-Type: application/json

###

// delete layoyuts behind some day's
GET http://{{host}}/api/v1/db/deleteOldLayouts/-1
Authorization: Bearer

###


// update all users worlds
GET http://{{host}}/api/v1/db/updateAllUsersWorlds
Authorization: Bearer

###


// create a new report
GET http://{{host}}/api/v1/db/createReport
Authorization: Bearer

###

// get the footer stats
GET http://{{host}}/api/v1/db/getFooterStats
Authorization: Bearer

###

