export const buildings = {
    r: 'Refinery',
    p: 'Power Plant',
    h: 'Harvester',
    y: 'Construction Yard',
    d: 'Airport',
    q: 'Defense HQ',
    b: 'Barracks',
    s: 'Silo',
    f: 'Factory',
    n: 'Harvester_Crystal',
    e: 'Command Post',
    z: 'Support_Art',
    i: 'Support_Ion',
    a: 'Accumulator',
    x: 'Support_Air',
    w: 'Defense Facility',
};

/* Forgotten Defense Units */
const for_def = {
    FOR_Wall: 'w',
    FOR_Barbwire_VS_Inf: 'b',
    FOR_Barrier_VS_Veh: 't',
    FOR_Inf_VS_Inf: 'g',
    FOR_Inf_VS_Veh: 'r',
    FOR_Inf_VS_Air: 'q',
    FOR_Sniper: 'n',
    FOR_Mammoth: 'y',
    FOR_Veh_VS_Inf: 'o',
    FOR_Veh_VS_Veh: 's',
    FOR_Veh_VS_Air: 'u',
    FOR_Turret_VS_Inf: 'm',
    FOR_Turret_VS_Inf_ranged: 'a',
    FOR_Turret_VS_Veh: 'v',
    FOR_Turret_VS_Veh_ranged: 'd',
    FOR_Turret_VS_Air: 'f',
    FOR_Turret_VS_Air_ranged: 'e',
};

/* GDI Defense Units */
const gdi_def = {
    GDI_Wall: 'w',
    GDI_Cannon: 'c',
    'GDI_Antitank Barrier': 't',
    GDI_Barbwire: 'b',
    GDI_Turret: 'm',
    GDI_Flak: 'f',
    'GDI_Art Inf': 'r',
    'GDI_Art Air': 'e',
    'GDI_Art Tank': 'a',
    'GDI_Def_APC Guardian': 'g',
    'GDI_Def_Missile Squad': 'q',
    GDI_Def_Pitbull: 'p',
    GDI_Def_Predator: 'd',
    GDI_Def_Sniper: 's',
    'GDI_Def_Zone Trooper': 'z',
};

/* Nod Defense Units */
const nod_def = {
    'NOD_Def_Antitank Barrier': 't',
    'NOD_Def_Art Air': 'e',
    'NOD_Def_Art Inf': 'r',
    'NOD_Def_Art Tank': 'a',
    'NOD_Def_Attack Bike': 'p',
    NOD_Def_Barbwire: 'b',
    'NOD_Def_Black Hand': 'z',
    NOD_Def_Cannon: 'c',
    NOD_Def_Confessor: 's',
    NOD_Def_Flak: 'f',
    'NOD_Def_MG Nest': 'm',
    'NOD_Def_Militant Rocket Soldiers': 'q',
    NOD_Def_Reckoner: 'g',
    'NOD_Def_Scorpion Tank': 'd',
    NOD_Def_Wall: 'w',
};
export default {
    army: {
        N: ['v', 't', 'r', 'l', 'b', 'a', 'o', 'p', 'k', 'm', 'q', 'z', 'c', 's'],
        G: ['a', 'o', 'f', 'k', 'g', 'p', 'd', 'm', 'j', 'r', 'q', 'z', 'c', 's'],
        F: [],
    },
    defense: {
        N: [
            'w',
            'c',
            't',
            'b',
            'a',
            'f',
            'r',
            'e',
            'm',
            'g',
            'd',
            'p',
            'q',
            's',
            'z',
            'h',
            'j',
            'k',
            'l',
        ],
        G: [
            'w',
            'c',
            't',
            'b',
            'a',
            'f',
            'r',
            'e',
            'm',
            'g',
            'd',
            'p',
            'q',
            's',
            'z',
            'h',
            'j',
            'k',
            'l',
        ],
        F: [
            'w',
            'b',
            't',
            'g',
            'r',
            'q',
            'n',
            'o',
            's',
            'u',
            'y',
            'm',
            'a',
            'v',
            'd',
            'f',
            'e',
            'h',
            'j',
            'k',
            'l',
        ],
    },
    buildings: {
        N: [
            't',
            'c',
            'h',
            'n',
            's',
            'r',
            'a',
            'p',
            'y',
            'd',
            'b',
            'f',
            'q',
            'w',
            'e',
            'z',
            'x',
            'i',
        ],
        G: [
            't',
            'c',
            'h',
            'n',
            's',
            'r',
            'a',
            'p',
            'y',
            'd',
            'b',
            'f',
            'q',
            'w',
            'e',
            'z',
            'x',
            'i',
        ],
        F: ['t', 'c', 'h', 'n', 's', 'b', 'v', 'r', 'u', 'y', 'q', 'w'],
    },
};


const keymap = {
    /* GDI Buildings */
    GDI_Accumulator: 'a',
    GDI_Refinery: 'r',
    'GDI_Trade Center': 'u',
    GDI_Silo: 's',
    'GDI_Power Plant': 'p',
    'GDI_Construction Yard': 'y',
    GDI_Airport: 'd',
    GDI_Barracks: 'b',
    GDI_Factory: 'f',
    'GDI_Defense HQ': 'q',
    'GDI_Defense Facility': 'w',
    'GDI_Command Center': 'e',
    GDI_Support_Art: 'z',
    GDI_Support_Air: 'x',
    GDI_Support_Ion: 'i',

    /* Forgotten Buildings */


    /* Nod Buildings */
    NOD_Refinery: 'r',
    'NOD_Power Plant': 'p',
    NOD_Harvester: 'h',
    'NOD_Construction Yard': 'y',
    NOD_Airport: 'd',
    'NOD_Trade Center': 'u',
    'NOD_Defense HQ': 'q',
    NOD_Barracks: 'b',
    NOD_Silo: 's',
    NOD_Factory: 'f',
    NOD_Harvester_Crystal: 'n',
    'NOD_Command Post': 'e',
    NOD_Support_Art: 'z',
    NOD_Support_Ion: 'i',
    NOD_Accumulator: 'a',
    NOD_Support_Air: 'x',
    'NOD_Defense Facility': 'w',
    //"NOD_Tech Lab": "",
    //"NOD_Recruitment Hub": "X",
    //"NOD_Temple of Nod": "X",

    /* GDI Offense Units */
    'GDI_APC Guardian': 'g',
    GDI_Commando: 'c',
    GDI_Firehawk: 'f',
    GDI_Juggernaut: 'j',
    GDI_Kodiak: 'k',
    GDI_Mammoth: 'm',
    'GDI_Missile Squad': 'q',
    GDI_Orca: 'o',
    GDI_Paladin: 'a',
    GDI_Pitbull: 'p',
    GDI_Predator: 'd',
    GDI_Riflemen: 'r',
    'GDI_Sniper Team': 's',
    'GDI_Zone Trooper': 'z',

    /* Nod Offense Units */
    'NOD_Attack Bike': 'b',
    NOD_Avatar: 'a',
    'NOD_Black Hand': 'z',
    NOD_Cobra: 'r',
    NOD_Commando: 'c',
    NOD_Confessor: 's',
    'NOD_Militant Rocket Soldiers': 'q',
    NOD_Militants: 'm',
    NOD_Reckoner: 'k',
    NOD_Salamander: 'l',
    'NOD_Scorpion Tank': 'o',
    'NOD_Specter Artilery': 'p',
    NOD_Venom: 'v',
    NOD_Vertigo: 't',
};

const defense_unit_map = {
    /* GDI Defense Units */
    GDI_Wall: 'w',
    GDI_Cannon: 'c',
    'GDI_Antitank Barrier': 't',
    GDI_Barbwire: 'b',
    GDI_Turret: 'm',
    GDI_Flak: 'f',
    'GDI_Art Inf': 'r',
    'GDI_Art Air': 'e',
    'GDI_Art Tank': 'a',
    'GDI_Def_APC Guardian': 'g',
    'GDI_Def_Missile Squad': 'q',
    GDI_Def_Pitbull: 'p',
    GDI_Def_Predator: 'd',
    GDI_Def_Sniper: 's',
    'GDI_Def_Zone Trooper': 'z',
    /* Nod Defense Units */
    'NOD_Def_Antitank Barrier': 't',
    'NOD_Def_Art Air': 'e',
    'NOD_Def_Art Inf': 'r',
    'NOD_Def_Art Tank': 'a',
    'NOD_Def_Attack Bike': 'p',
    NOD_Def_Barbwire: 'b',
    'NOD_Def_Black Hand': 'z',
    NOD_Def_Cannon: 'c',
    NOD_Def_Confessor: 's',
    NOD_Def_Flak: 'f',
    'NOD_Def_MG Nest': 'm',
    'NOD_Def_Militant Rocket Soldiers': 'q',
    NOD_Def_Reckoner: 'g',
    'NOD_Def_Scorpion Tank': 'd',
    NOD_Def_Wall: 'w',

    /* Forgotten Defense Units */
    FOR_Wall: 'w',
    FOR_Barbwire_VS_Inf: 'b',
    FOR_Barrier_VS_Veh: 't',
    FOR_Inf_VS_Inf: 'g',
    FOR_Inf_VS_Veh: 'r',
    FOR_Inf_VS_Air: 'q',
    FOR_Sniper: 'n',
    FOR_Mammoth: 'y',
    FOR_Veh_VS_Inf: 'o',
    FOR_Veh_VS_Veh: 's',
    FOR_Veh_VS_Air: 'u',
    FOR_Turret_VS_Inf: 'm',
    FOR_Turret_VS_Inf_ranged: 'a',
    FOR_Turret_VS_Veh: 'v',
    FOR_Turret_VS_Veh_ranged: 'd',
    FOR_Turret_VS_Air: 'f',
    FOR_Turret_VS_Air_ranged: 'e',
    '': '',
};

const offense_unit_map = {
    /* GDI Offense Units */
    'GDI_APC Guardian': 'g',
    GDI_Commando: 'c',
    GDI_Firehawk: 'f',
    GDI_Juggernaut: 'j',
    GDI_Kodiak: 'k',
    GDI_Mammoth: 'm',
    'GDI_Missile Squad': 'q',
    GDI_Orca: 'o',
    GDI_Paladin: 'a',
    GDI_Pitbull: 'p',
    GDI_Predator: 'd',
    GDI_Riflemen: 'r',
    'GDI_Sniper Team': 's',
    'GDI_Zone Trooper': 'z',

    /* Nod Offense Units */
    'NOD_Attack Bike': 'b',
    NOD_Avatar: 'a',
    'NOD_Black Hand': 'z',
    NOD_Cobra: 'r',
    NOD_Commando: 'c',
    NOD_Confessor: 's',
    'NOD_Militant Rocket Soldiers': 'q',
    NOD_Militants: 'm',
    NOD_Reckoner: 'k',
    NOD_Salamander: 'l',
    'NOD_Scorpion Tank': 'o',
    'NOD_Specter Artilery': 'p',
    NOD_Venom: 'v',
    NOD_Vertigo: 't',
};


// export const nod_buildings = {
//     r: 'NOD_Refinery',
//     p: 'NOD_Power Plant',
//     h: 'NOD_Harvester',
//     y: 'NOD_Construction Yard',
//     d: 'NOD_Airport',
//     q: 'NOD_Defense HQ',
//     b: 'NOD_Barracks',
//     s: 'NOD_Silo',
//     f: 'NOD_Factory',
//     n: 'NOD_Harvester_Crystal',
//     e: 'NOD_Command Post',
//     z: 'NOD_Support_Art',
//     i: 'NOD_Support_Ion',
//     a: 'NOD_Accumulator',
//     x: 'NOD_Support_Air',
//     w: 'NOD_Defense Facility',
// };

/*var nod_buildings_names = {
 "NOD_Refinery": "r",
 "NOD_Power Plant": "p",
 "NOD_Harvester": "h",
 "NOD_Construction Yard": "y",
 "NOD_Airport": "d",
 //    "NOD_Trade Center": "u",
 "NOD_Defense HQ": "q",
 "NOD_Barracks": "b",
 "NOD_Silo": "s",
 "NOD_Factory": "f",
 "NOD_Harvester_Crystal": "n",
 "NOD_Command Post": "e",
 "NOD_Support_Art": "z",
 "NOD_Support_Ion": "i",
 "NOD_Accumulator": "a",
 "NOD_Support_Air": "x",
 "NOD_Defense Facility": "w"
 },
 nod_buildings_keys = {
 "r": "NOD_Refinery",
 "p": "NOD_Power Plant",
 "h": "NOD_Harvester",
 "y": "NOD_Construction Yard",
 "d": "NOD_Airport",
 "q": "NOD_Defense HQ",
 "b": "NOD_Barracks",
 "s": "NOD_Silo",
 "f": "NOD_Factory",
 "n": "NOD_Harvester_Crystal",
 "e": "NOD_Command Post",
 "z": "NOD_Support_Art",
 "i": "NOD_Support_Ion",
 "a": "NOD_Accumulator",
 "x": "NOD_Support_Air",
 "w": "NOD_Defense Facility"
 }
 */
