export const buildingKeys = [
    't',
    'c',
    'h',
    'n',
    's',
    'r',
    'a',
    'p',
    'y',
    'd',
    'b',
    'f',
    'q',
    'w',
    'e',
    'z',
    'x',
    'i',
];

export const buildings = {
    r: 'Refinery',
    p: 'Power Plant',
    h: 'Harvester',
    y: 'Construction Yard',
    d: 'Airport',
    q: 'Defense HQ',
    b: 'Barracks',
    s: 'Silo',
    f: 'Factory',
    n: 'Harvester_Crystal',
    e: 'Command Post',
    z: 'Support_Art',
    i: 'Support_Ion',
    a: 'Accumulator',
    x: 'Support_Air',
    w: 'Defense Facility',
};

export default {
    army: {
        N: ['v', 't', 'r', 'l', 'b', 'a', 'o', 'p', 'k', 'm', 'q', 'z', 'c', 's'],
        G: ['a', 'o', 'f', 'k', 'g', 'p', 'd', 'm', 'j', 'r', 'q', 'z', 'c', 's'],
    },
    defense: {
        N: [
            'w',
            'c',
            't',
            'b',
            'a',
            'f',
            'r',
            'e',
            'm',
            'g',
            'd',
            'p',
            'q',
            's',
            'z',
            'h',
            'j',
            'k',
            'l',
        ],
        G: [
            'w',
            'c',
            't',
            'b',
            'a',
            'f',
            'r',
            'e',
            'm',
            'g',
            'd',
            'p',
            'q',
            's',
            'z',
            'h',
            'j',
            'k',
            'l',
        ],
    },
    buildings: {
        N: [
            't',
            'c',
            'h',
            'n',
            's',
            'r',
            'a',
            'p',
            'y',
            'd',
            'b',
            'f',
            'q',
            'w',
            'e',
            'z',
            'x',
            'i',
        ],
        G: [
            't',
            'c',
            'h',
            'n',
            's',
            'r',
            'a',
            'p',
            'y',
            'd',
            'b',
            'f',
            'q',
            'w',
            'e',
            'z',
            'x',
            'i',
        ],
    },
};

// export const nod_buildings = {
//     r: 'NOD_Refinery',
//     p: 'NOD_Power Plant',
//     h: 'NOD_Harvester',
//     y: 'NOD_Construction Yard',
//     d: 'NOD_Airport',
//     q: 'NOD_Defense HQ',
//     b: 'NOD_Barracks',
//     s: 'NOD_Silo',
//     f: 'NOD_Factory',
//     n: 'NOD_Harvester_Crystal',
//     e: 'NOD_Command Post',
//     z: 'NOD_Support_Art',
//     i: 'NOD_Support_Ion',
//     a: 'NOD_Accumulator',
//     x: 'NOD_Support_Air',
//     w: 'NOD_Defense Facility',
// };

/*var nod_buildings_names = {
 "NOD_Refinery": "r",
 "NOD_Power Plant": "p",
 "NOD_Harvester": "h",
 "NOD_Construction Yard": "y",
 "NOD_Airport": "d",
 //    "NOD_Trade Center": "u",
 "NOD_Defense HQ": "q",
 "NOD_Barracks": "b",
 "NOD_Silo": "s",
 "NOD_Factory": "f",
 "NOD_Harvester_Crystal": "n",
 "NOD_Command Post": "e",
 "NOD_Support_Art": "z",
 "NOD_Support_Ion": "i",
 "NOD_Accumulator": "a",
 "NOD_Support_Air": "x",
 "NOD_Defense Facility": "w"
 },
 nod_buildings_keys = {
 "r": "NOD_Refinery",
 "p": "NOD_Power Plant",
 "h": "NOD_Harvester",
 "y": "NOD_Construction Yard",
 "d": "NOD_Airport",
 "q": "NOD_Defense HQ",
 "b": "NOD_Barracks",
 "s": "NOD_Silo",
 "f": "NOD_Factory",
 "n": "NOD_Harvester_Crystal",
 "e": "NOD_Command Post",
 "z": "NOD_Support_Art",
 "i": "NOD_Support_Ion",
 "a": "NOD_Accumulator",
 "x": "NOD_Support_Air",
 "w": "NOD_Defense Facility"
 }
 */
