// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const CHANGE_AUTH_EMAIL = 'CHANGE_AUTH_EMAIL'
export const CHANGE_AUTH_PASSWORD = 'CHANGE_AUTH_PASSWORD'

// base
export const REPLACE_BUILDING = "REPLACE_BUILDING"
export const REPLACE_ALL_BASE = "REPLACE_ALL_BASE"
export const REPLACE_BASE_FROM_URL = "REPLACE_BASE_FROM_URL"
export const CHANGE_FRACTION = "CHANGE_FRACTION"
export const BUILDING_TYP_UP = "BUILDING_TYP_UP"
export const BUILDING_TYP_DOWN = "BUILDING_TYP_DOWN"

// player
export const CHANGE_PLAYER = "CHANGE_PLAYER"
export const CHANGE_WORLD = "CHANGE_WORLD"
export const CHANGE_ALLIANCE = "CHANGE_ALLIANCE"